In [1]:
import numpy as np

In [3]:
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [4]:
np.array(list)

array([1, 2, 3, 4])

In [3]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np.array(matriz)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
matriz[0][2]

3

In [7]:
# shift + tab para ver os parâmetros do método
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [14]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [15]:
np.random.rand(5,4)

array([[0.24784993, 0.22389541, 0.18332656, 0.98238424],
       [0.75184953, 0.15017269, 0.85109249, 0.12739234],
       [0.12916006, 0.97400096, 0.85139935, 0.20681095],
       [0.33236463, 0.39558345, 0.53767527, 0.6700305 ],
       [0.03061163, 0.46921823, 0.23201994, 0.26568149]])

In [16]:
np.random.randn(5,4)

array([[ 0.38382081,  1.98069482, -1.61437145, -1.66787635],
       [-0.31395651,  1.46174251,  1.11269661, -0.34536656],
       [ 1.08119726, -0.19423393,  0.9726692 , -1.09353725],
       [ 0.06965219,  0.15129172,  0.4972213 , -0.4925416 ],
       [ 1.64994631,  0.18970712, -2.64062544, -1.48496135]])

In [17]:
np.random.randint(0, 100, 10)

array([94, 13, 46, 45, 58, 28, 48, 23, 67, 89])

In [18]:
matrix = np.random.randint(0, 100, (5,5))
matrix

array([[82,  4, 89, 36, 50],
       [90, 81,  8,  6, 87],
       [14, 86, 30, 70, 65],
       [ 8, 14, 68,  8, 60],
       [26, 93, 39, 13, 25]])

In [19]:
matrix.shape

(5, 5)

In [20]:
matrix.min()

4

In [21]:
matrix.max()

93

In [22]:
matrix.argmax()

21

In [23]:
# AULA DE INDEXAÇÃO E FATIAMENTO DE ARRAYS

In [24]:
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [25]:
arr[3]

9

In [26]:
arr[2:5]

array([ 6,  9, 12])

In [27]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [28]:
arr[5:]

array([15, 18, 21, 24, 27])

In [29]:
arr[:6] = 100
arr

array([100, 100, 100, 100, 100, 100,  18,  21,  24,  27])

In [30]:
arr = np.arange(50).reshape((5,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
# Pegando as 3 primeiras linhas de todas as colunas
arr[:3][:] #equivalente à arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [32]:
arr2 = arr[:3] #arr2 é uma referência às 3 linhas do arr, uma vez alterado altera o arr também
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [33]:
arr3 = arr[:3].copy() #Forma correta de copiar o array
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
arr[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [35]:
# Pegando os valores das linhas 1 e 2 e colunas até 4
arr[1:3,:5]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [36]:
arr > 25

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [37]:
arr[arr>25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [38]:
mat = np.random.randint(0, 100, (3,10))
mat

array([[78, 17, 37, 46, 36, 86, 54,  4, 26, 31],
       [55, 62,  0, 71, 75, 39, 17, 43, 75, 83],
       [72, 98, 93, 15, 33, 15, 91, 42,  6, 22]])

In [39]:
mat[:2, 3:8]

array([[46, 36, 86, 54,  4],
       [71, 75, 39, 17, 43]])

In [41]:
# pegando o index onde está contido o valor 89
i, j = np.where(mat == 86)
print(i[0])
print(j[0])

0
5


In [42]:
# AULA DE OPERAÇÕES COM NUMPY ARRAYS

In [43]:
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [45]:
arr - arr 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [47]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [48]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [49]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [50]:
np.max(arr)

19

In [51]:
# https://numpy.org/doc/stable/reference/